### ISSUE TITLE
private method `print' called for nil:NilClass

### ISSUE THREAD

**Issue by jfedgar** [ruby/vscode-rdbg#1]
This might be because i'm using the preview on 3.0.1. However, when I invoke the debugger (f5) and enter into the "Debug Command Line" the following `ruby /Users/joeed/test/blah.rb ` 

I get the following error:

```
/Users/joeed/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.0.0.rc2/lib/debug/server_dap.rb:85:in `send': private method `print' called for nil:NilClass (NoMethodError)
        from /Users/joeed/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.0.0.rc2/lib/debug/server_dap.rb:110:in `send_event'
        from /Users/joeed/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.0.0.rc2/lib/debug/server_dap.rb:259:in `event'
        from /Users/joeed/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.0.0.rc2/lib/debug/session.rb:193:in `session_server_main'
```

If I enter:

`rdbg -c ruby /Users/joeed/unifi/test/blah.rb`
or
`rdbg /Users/joeed/unifi/test/blah.rb`

They work and drop me into a debugger session in the terminal. However the "Watch", "Call Stack" and "Variables" sections are not populated in VSCode (i'm not sure if they are supposed to be or if that hasn't been implemented in this plugin yet)

**Comment by jfedgar** [comment]
The complete error:

```
DEBUGGER: Session start (pid: 74540)
DEBUGGER: Debugger can attach via UNIX domain socket (/Users/joeed/.ruby-debug-sock/ruby-debug-joeed-74409)
DEBUGGER: wait for debugger connection...
DEBUGGER: Connected.
DEBUGGER: ReaderThreadError: undefined method `add_catch_breakpoint' for DEBUGGER__::SESSION:DEBUGGER__::Session
Did you mean?  add_check_breakpoint
               add_line_breakpoint
DEBUGGER: Disconnected.
#<Thread:0x00007fcbb001d168@DEBUGGER__::SESSION@server /Users/joeed/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.0.0.rc2/lib/debug/session.rb:110 run> terminated with exception (report_on_exception is true):
/Users/joeed/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.0.0.rc2/lib/debug/server_dap.rb:85:in `send': private method `print' called for nil:NilClass (NoMethodError)
        from /Users/joeed/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.0.0.rc2/lib/debug/server_dap.rb:110:in `send_event'
        from /Users/joeed/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.0.0.rc2/lib/debug/server_dap.rb:259:in `event'
        from /Users/joeed/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.0.0.rc2/lib/debug/session.rb:193:in `session_server_main'
        from /Users/joeed/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.0.0.rc2/lib/debug/session.rb:113:in `block in activate'
["DEBUGGER Exception: /Users/joeed/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.0.0.rc2/lib/debug/thread_client.rb:956",
 #<NoMethodError: private method `print' called for nil:NilClass>,
 ["/Users/joeed/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.0.0.rc2/lib/debug/server_dap.rb:85:in `send'",
  "/Users/joeed/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.0.0.rc2/lib/debug/server_dap.rb:110:in `send_event'",
  "/Users/joeed/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.0.0.rc2/lib/debug/server_dap.rb:259:in `event'",
  "/Users/joeed/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.0.0.rc2/lib/debug/session.rb:193:in `session_server_main'",
  "/Users/joeed/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.0.0.rc2/lib/debug/session.rb:113:in `block in activate'"]]
/Users/joeed/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.0.0.rc2/lib/debug/server_dap.rb:85:in `send': private method `print' called for nil:NilClass (NoMethodError)
        from /Users/joeed/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.0.0.rc2/lib/debug/server_dap.rb:110:in `send_event'
        from /Users/joeed/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.0.0.rc2/lib/debug/server_dap.rb:259:in `event'
        from /Users/joeed/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.0.0.rc2/lib/debug/session.rb:193:in `session_server_main'
        from /Users/joeed/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.0.0.rc2/lib/debug/session.rb:113:in `block in activate'
        ```

**Comment by ko1** [comment]
Thank you for your report. Could you share us your trial script?

**Comment by ko1** [comment]
Please open this issue if your script if you still have a issue on latest version.
