### ISSUE TITLE
Fails to run on a Windows PC

### ISSUE THREAD

**Issue by belgoros** [ruby/vscode-rdbg#58]
VS code version:

```
Version: 1.68.1 (system setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19042
```
Ruby version installed with [scoop.sh](https://scoop.sh/):
```
ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x64-mingw-ucrt]
```

Debug gem version: `1.6.2`.
Here is the `launch.json` file content generated by VS Code with no additional changes:
```json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "rdbg",
      "name": "Debug current file with rdbg",
      "request": "launch",
      "script": "${file}",
      "args": [],
      "askParameters": true
    },
    {
      "type": "rdbg",
      "name": "Attach with rdbg",
      "request": "attach"
    }
  ]
}
```
When running a simple ruby script with a break point enabled:
![image](https://user-images.githubusercontent.com/83579/192999714-1e10463c-4d85-48a3-90ca-950e51e62e36.png)

it raises the error:
```
C:/Users/scambour/scoop/persist/ruby/gems/gems/debug-1.6.2/lib/debug/config.rb:415:in `check_dir_authority': C:/Users/scambour/AppData/Local/Temp/ruby-debug-sock-0's mode is 40755 (should be 040700) (RuntimeError)
	from C:/Users/scambour/scoop/persist/ruby/gems/gems/debug-1.6.2/lib/debug/config.rb:432:in `unix_domain_socket_tmpdir'
	from C:/Users/scambour/scoop/persist/ruby/gems/gems/debug-1.6.2/lib/debug/config.rb:452:in `unix_domain_socket_dir'
	from C:/Users/scambour/scoop/persist/ruby/gems/gems/debug-1.6.2/lib/debug/config.rb:466:in `create_unix_domain_socket_name'
	from C:/Users/scambour/scoop/persist/ruby/gems/gems/debug-1.6.2/lib/debug/client.rb:20:in `util'
	from C:/Users/scambour/scoop/persist/ruby/gems/gems/debug-1.6.2/lib/debug/config.rb:368:in `block (2 levels) in parse_argv'
	from C:/Users/scambour/scoop/apps/ruby/3.1.2-1/lib/ruby/3.1.0/optparse.rb:1576:in `block in parse_in_order'
	from C:/Users/scambour/scoop/apps/ruby/3.1.2-1/lib/ruby/3.1.0/optparse.rb:1559:in `catch'
	from C:/Users/scambour/scoop/apps/ruby/3.1.2-1/lib/ruby/3.1.0/optparse.rb:1559:in `parse_in_order'
	from C:/Users/scambour/scoop/apps/ruby/3.1.2-1/lib/ruby/3.1.0/optparse.rb:1553:in `order!'
	from C:/Users/scambour/scoop/apps/ruby/3.1.2-1/lib/ruby/3.1.0/optparse.rb:1659:in `permute!'
	from C:/Users/scambour/scoop/apps/ruby/3.1.2-1/lib/ruby/3.1.0/optparse.rb:1684:in `parse!'
	from C:/Users/scambour/scoop/persist/ruby/gems/gems/debug-1.6.2/lib/debug/config.rb:382:in `parse_argv'
	from C:/Users/scambour/scoop/persist/ruby/gems/gems/debug-1.6.2/exe/rdbg:4:in `<top (required)>'
	from C:/Users/scambour/scoop/apps/ruby/current/gems/bin/rdbg:32:in `load'
	from C:/Users/scambour/scoop/apps/ruby/current/gems/bin/rdbg:32:in `<main>'

Error: exit code is 1
Make sure to install rdbg command (`gem install debug`).
If you are using bundler, write `gem 'debug'` in your Gemfile.
[Start session]
{"_debugServiceProxy":{},"_id":"93cf4047-1bd0-4a84-a732-48ff1e037a69","_type":"rdbg","_name":"Debug current file with rdbg","_workspaceFolder":{"uri":{"$mid":1,"fsPath":"c:\\Users\\scambour\\Exercism\\ruby\\accumulate","_sep":1,"external":"file:///c%3A/Users/scambour/Exercism/ruby/accumulate","path":"/c:/Users/scambour/Exercism/ruby/accumulate","scheme":"file"},"name":"accumulate","index":0},"_configuration":{"type":"rdbg","name":"Debug current file with rdbg","request":"launch","script":"extension-output-KoichiSasada.vscode-rdbg-#1-rdbg","args":[],"askParameters":true,"__configurationTarget":5}}
```

**Comment by ko1** [comment]
Now Windows only runs with `debugPort` configuration (TCP/IP).
Could you try it?>

**Comment by belgoros** [comment]
@ko1 could you please point out how I can try/set it? Thank you.

**Comment by ko1** [comment]
https://github.com/ruby/vscode-rdbg
![image](https://user-images.githubusercontent.com/9558/194459252-18f1d84d-1918-4684-9742-789cf87f8835.png)


if you want to attach to the Ruby process, please use `rdbg -O --port 12345 <your script>` to open TCP/IP port 12345.

**Comment by belgoros** [comment]
OK, here is the updated `launh.json` file:
```json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "rdbg",
      "name": "Debug current file with rdbg",
      "request": "launch",
      "script": "${file}",
      "args": [],
      "askParameters": true,
      "debugPort": "localhost:12345"
    },
    {
      "type": "rdbg",
      "name": "Attach with rdbg",
      "request": "attach"
    }
  ]
}
```
When running a ruby script by selecting the option "Debug current file with rdbg" (see below):
![image](https://user-images.githubusercontent.com/83579/194492034-06144295-d828-4d81-b1a8-e950a60307a9.png)
I'm asked to choose from:
![image](https://user-images.githubusercontent.com/83579/194493151-916150c1-f9ef-43bb-bf0b-6b274f261ed9.png)
and here is the output in the VS code terminal:
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\scambour\myprojects\ruby\ruby_drafts> rdbg --command --open --stop-at-load --port=12345 --host=localhost -- bundle exec ruby c:\Users\scambour\myprojects\ruby\ruby_drafts\lib\demo.rb
DEBUGGER: Debugger can attach via TCP/IP (127.0.0.1:12345)
DEBUGGER: wait for debugger connection...
``` 
Hitting the `CTRL-C` results in: 
```
C:/Users/scambour/scoop/persist/ruby/gems/gems/debug-1.6.2/lib/debug/thread_client.rb:815:in `pop': Interrupt
        from C:/Users/scambour/scoop/persist/ruby/gems/gems/debug-1.6.2/lib/debug/thread_client.rb:815:in `wait_next_action_'
        from C:/Users/scambour/scoop/persist/ruby/gems/gems/debug-1.6.2/lib/debug/thread_client.rb:797:in `wait_next_action' 
        from C:/Users/scambour/scoop/persist/ruby/gems/gems/debug-1.6.2/lib/debug/thread_client.rb:310:in `suspend'
        from C:/Users/scambour/scoop/persist/ruby/gems/gems/debug-1.6.2/lib/debug/thread_client.rb:243:in `on_breakpoint'    
        from C:/Users/scambour/scoop/persist/ruby/gems/gems/debug-1.6.2/lib/debug/breakpoint.rb:69:in `suspend'
        from C:/Users/scambour/scoop/persist/ruby/gems/gems/debug-1.6.2/lib/debug/breakpoint.rb:169:in `block in setup'      
        from C:/Users/scambour/scoop/persist/ruby/gems/gems/debug-1.6.2/lib/debug/session.rb:2080:in `setup_initial_suspend'
        from C:/Users/scambour/scoop/persist/ruby/gems/gems/debug-1.6.2/lib/debug/session.rb:2057:in `open_tcp'
        from C:/Users/scambour/scoop/persist/ruby/gems/gems/debug-1.6.2/lib/debug/session.rb:2041:in `open'
        from C:/Users/scambour/scoop/persist/ruby/gems/gems/debug-1.6.2/lib/debug/open.rb:13:in `<top (required)>'
        from c:/Users/scambour/myprojects/ruby/ruby_drafts/lib/demo.rb:in `require'
Terminate batch job (Y/N)? 
```
I've never entered into the `demo.rb` file in debug mode.

**Comment by ko1** [comment]
Wow I'm not sure why it doesn't connect to Ruby... I'll try it.

**Comment by TheGuardianWolf** [comment]
I can confirm the debugger has issues, it does not respect breakpoints.

I placed a breakpoint on line 2 that emits "test2"
![image](https://user-images.githubusercontent.com/8168401/198422020-97a24aca-45c7-4c5d-84ab-9a1697ab5ee8.png)

**Comment by ko1** [comment]
The original issue may be fixed and breakpoint issue should be separated (@ono-max san will make an issue)
