### ISSUE TITLE
Question on integrating with vimspector

### ISSUE THREAD

**Issue by st0012** [ruby/vscode-rdbg#7]
Hello, I'm trying to integrate `ruby/debug` with [vimspector](https://github.com/puremourning/vimspector) (a vim plugin that provides DAP support) via this project.

Although it doesn't support any Ruby debugger atm, it provides [instruction](https://github.com/puremourning/vimspector/wiki/languages#ruby) for setting up [`vscode-ruby`'s debugger](https://github.com/rubyide/vscode-ruby/tree/main/packages/vscode-ruby-debugger). So I'm trying to figure out a similar setting for integrating it with `vscode-rdbg` too. But I encountered some problems when doing this:

For every adapter,`vimspector` requires a command to kick off the DAP server. 

You can see built-in adapters' settings [here](https://github.com/puremourning/vimspector/blob/master/python3/vimspector/gadgets.py). And the instruction for `vscode-ruby` also has a command:

```
          "command": [
            "node",
            "${gadgetDir}/cust_vscode-ruby/dist/debugger/main.js"
          ],
```

[debugger/main.js](https://github.com/rubyide/vscode-ruby/blob/main/packages/vscode-ruby-debugger/src/main.ts)

And I'm using a similar config like

```json
{
  "cust_vscode-rdbg": {
    "language": "ruby",
    "download": {
      "url": "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/KoichiSasada/vsextensions/vscode-rdbg/${version}/vspackage",
      "target": "vscode-rdbg.vsix.gz",
      "format": "zip.gz"
    },
    "all": {
      "version": "0.0.5",
      "file_name": "vscode-rdbg.vsix.gz",
      "adapters": {
        "cust_vscode-rdbg": {
          "command": [
            "node",
            "${gadgetDir}/download/cust_vscode-rdbg/0.0.5/root/extension/out/extension.js"
          ],
          "name": "vscode-rdbg",
          "configuration": {
            "cwd": "${workspaceRoot}",
            "showDebugOutput": true,
            "trace": true
          }
        }
      }
    }
  }
}
```

However, it doesn't work:

```
2021-09-12 00:33:00,670 - INFO - User requested start debug session with {}
2021-09-12 00:33:00,671 - DEBUG - Reading configurations from: None
2021-09-12 00:33:00,671 - DEBUG - Reading configurations from: /Users/st0012/projects/sentry-ruby/sentry-ruby/.vimspector.json
2021-09-12 00:33:00,672 - DEBUG - Reading gadget config: /Users/st0012/.config/nvim/plugged/vimspector/gadgets/macos/.gadgets.json
2021-09-12 00:33:00,672 - DEBUG - Reading gadget config: None
2021-09-12 00:33:00,673 - INFO - Configuration: {"adapter": "cust_vscode-rdbg", "default": true, "configuration": {"name": "Run RSpec with debugger", "request": "launch", "command": "bundle exec rspec", "args": ["/Users/st0012/projects/sentry-ruby/sentry-ruby/_vimspector_log_Vimspector"]}}
2021-09-12 00:33:00,673 - INFO - Adapter: {"command": ["node", "/Users/st0012/.config/nvim/plugged/vimspector/gadgets/macos/download/cust_vscode-rdbg/0.0.5/root/extension/out/extension.js"], "configuration": {"cwd": "/Users/st0012/projects/sentry-ruby/sentry-ruby", "showDebugOutput": true, "trace": true}, "name": "vscode-rdbg"}
2021-09-12 00:33:00,674 - DEBUG - min_width/height: 149/50, actual: 188/84 - result: horizontal
2021-09-12 00:33:00,760 - DEBUG - LAUNCH!

# check this line
2021-09-12 00:33:00,765 - INFO - Starting debug adapter with: {"command": ["node", "/Users/st0012/.config/nvim/plugged/vimspector/gadgets/macos/download/cust_vscode-rdbg/0.0.5/root/extension/out/extension.js"], "configuration": {"cwd": "/Users/st0012/projects/sentry-ruby/sentry-ruby", "showDebugOutput": true, "trace": true}, "name": "vscode-rdbg"}
2021-09-12 00:33:00,765 - DEBUG - Connection Type: neojob
2021-09-12 00:33:00,768 - INFO - Debug Adapter Started
2021-09-12 00:33:00,768 - DEBUG - Sending Message: {"command": "initialize", "arguments": {"adapterID": "vscode-rdbg", "clientID": "vimspector", "clientName": "vimspector", "linesStartAt1": true, "columnsStartAt1": true, "locale": "en_GB", "pathFormat": "path", "supportsVariableType": true, "supportsVariablePaging": false, "supportsRunInTerminalRequest": true}, "seq": 0, "type": "request"}
2021-09-12 00:33:00,826 - INFO - The server has terminated with status 1
2021-09-12 00:33:00,829 - DEBUG - Closing down: Aborting request {'command': 'initialize', 'arguments': {'adapterID': 'vscode-rdbg', 'clientID': 'vimspector', 'clientName': 'vimspector', 'linesStartAt1': True, 'columnsStartAt1': True, 'locale': 'en_GB', 'pathFormat': 'path', 'supportsVariableType': True, 'supportsVariablePaging': False, 'supportsRunInTerminalRequest': True}, 'seq': 0, 'type': 'request'}
2021-09-12 00:33:00,829 - INFO - User Msg: Request for initialize aborted: Closing down
2021-09-12 00:33:00,831 - DEBUG - No server exit handler
2021-09-12 00:33:00,826 - INFO - The server has terminated with status 1
2021-09-12 00:33:00,829 - DEBUG - Closing down: Aborting request {'command': 'initialize', 'arguments': {'adapterID': 'vscode-rdbg', 'clientID': 'vimspector', 'clientName': 'vimspector', 'linesStartAt1': True, 'columnsStartAt1': True, 'locale': 'en_GB', 'pathFormat': 'path', 'supportsVariableType': True, 'supportsVariablePaging': False, 'supportsRunInTerminalRequest': True}, 'seq': 0, 'type': 'request'}
2021-09-12 00:33:00,829 - INFO - User Msg: Request for initialize aborted: Closing down
```

And when I manually run the command, I got 

```
❯ node /Users/st0012/.config/nvim/plugged/vimspector/gadgets/macos/download/cust_vscode-rdbg/0.0.5/root/extension/out/extension.js
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'vscode'
Require stack:
- /Users/st0012/projects/configs/nvim/plugged/vimspector/gadgets/macos/download/cust_vscode-rdbg/0.0.5/root/extension/out/extension.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/st0012/projects/configs/nvim/plugged/vimspector/gadgets/macos/download/cust_vscode-rdbg/0.0.5/root/extension/out/extension.js:17:16)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/st0012/projects/configs/nvim/plugged/vimspector/gadgets/macos/download/cust_vscode-rdbg/0.0.5/root/extension/out/extension.js'
  ]
}
```

Since I can't find `vscode` in this project's `package.json`, I'm not sure if it's the `vscode` editor itself. If it is, would it be possible to make it work similar to [vscode-ruby/debugger/main.js](https://github.com/rubyide/vscode-ruby/blob/main/packages/vscode-ruby-debugger/src/main.ts), which doesn't require `vscode`?
Or do I misunderstand something? (which is very likely as I've never worked with vscode and anything relate to it until today).

**Comment by ko1** [comment]
Sorry I didn't check it.
Now vscode-rdbg depends on `vscode.DebugAdapter*` so we can't make similar to vscode-ruby approach.
